export const CATEGORY_CONFIG = {
  fashion: {
    label: "Fashion & Clothing",
    emoji: "👗",
    description: "Clothes, shoes, accessories and more",
    terminology: {
      product: "Item",
      order: "Order",
      customer: "Shopper",
      sale: "Sale",
    },
    productFields: ["size", "color", "material", "gender"],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: true,
      expiry: false,
    },
    defaultCategories: ["Men", "Women", "Kids", "Shoes", "Bags", "Accessories"],
    keywords: [
      "cloth",
      "fashion",
      "wear",
      "dress",
      "shirt",
      "trouser",
      "shoe",
      "bag",
      "gown",
      "sneaker",
      "cap",
      "jean",
    ],
  },

  food: {
    label: "Food & Catering",
    emoji: "🍔",
    description: "Restaurants, caterers, food vendors",
    terminology: {
      product: "Meal",
      order: "Order",
      customer: "Customer",
      sale: "Sale",
    },
    productFields: ["portion", "prepTime", "deliveryArea", "spiceLevel"],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: false,
      expiry: false,
    },
    defaultCategories: [
      "Rice Dishes",
      "Soups",
      "Snacks",
      "Drinks",
      "Pastries",
      "Grills",
    ],
    keywords: [
      "food",
      "meal",
      "eat",
      "hungry",
      "rice",
      "soup",
      "chicken",
      "beef",
      "fish",
      "drink",
      "snack",
      "order food",
    ],
  },

  beauty: {
    label: "Beauty & Salon",
    emoji: "💅",
    description: "Hair salons, spas, beauty services",
    terminology: {
      product: "Service",
      order: "Appointment",
      customer: "Client",
      sale: "Service",
    },
    productFields: ["duration", "stylist", "serviceType"],
    features: {
      delivery: false,
      productPhotos: true,
      catalog: true,
      appointments: true,
      inventory: false,
      expiry: false,
    },
    defaultCategories: [
      "Hair",
      "Nails",
      "Makeup",
      "Skincare",
      "Lashes",
      "Brows",
    ],
    keywords: [
      "hair",
      "nail",
      "makeup",
      "lash",
      "brow",
      "skin",
      "beauty",
      "salon",
      "appointment",
      "book",
      "style",
    ],
  },

  pharmacy: {
    label: "Pharmacy",
    emoji: "💊",
    description: "Pharmacies, drug stores, medical supplies",
    terminology: {
      product: "Product",
      order: "Order",
      customer: "Patient",
      sale: "Dispensing",
    },
    productFields: ["dosage", "manufacturer", "expiryDate", "prescription"],
    features: {
      delivery: true,
      productPhotos: false,
      catalog: true,
      appointments: false,
      inventory: true,
      expiry: true,
    },
    defaultCategories: [
      "Drugs",
      "Supplements",
      "Baby Care",
      "Skincare",
      "Medical Supplies",
      "OTC",
    ],
    keywords: [
      "drug",
      "medicine",
      "tablet",
      "syrup",
      "prescription",
      "pain",
      "fever",
      "vitamin",
      "supplement",
    ],
  },

  electronics: {
    label: "Electronics",
    emoji: "📱",
    description: "Phones, gadgets, electronics repair",
    terminology: {
      product: "Product",
      order: "Order",
      customer: "Customer",
      sale: "Sale",
    },
    productFields: ["brand", "model", "warranty", "color", "storage"],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: true,
      expiry: false,
    },
    defaultCategories: [
      "Phones",
      "Laptops",
      "Accessories",
      "Audio",
      "Gaming",
      "Repairs",
    ],
    keywords: [
      "phone",
      "laptop",
      "gadget",
      "charger",
      "earphone",
      "screen",
      "battery",
      "repair",
      "iphone",
      "samsung",
    ],
  },

  pos: {
    label: "POS & Financial Services",
    emoji: "💳",
    description: "POS agents, money transfer, financial services",
    terminology: {
      product: "Service",
      order: "Transaction",
      customer: "Customer",
      sale: "Transaction",
    },
    productFields: ["transactionType", "commission", "agentCode"],
    features: {
      delivery: false,
      productPhotos: false,
      catalog: false,
      appointments: false,
      inventory: false,
      expiry: false,
    },
    defaultCategories: ["Withdrawal", "Transfer", "Airtime", "Bills", "Data"],
    keywords: [
      "pos",
      "transfer",
      "withdrawal",
      "atm",
      "cash",
      "send money",
      "airtime",
      "data",
      "bill",
    ],
  },

  grocery: {
    label: "Grocery & Supermarket",
    emoji: "🛒",
    description: "Grocery stores, supermarkets, provisions",
    terminology: {
      product: "Item",
      order: "Order",
      customer: "Customer",
      sale: "Sale",
    },
    productFields: ["unit", "weight", "brand", "expiryDate"],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: true,
      expiry: true,
    },
    defaultCategories: [
      "Grains & Rice",
      "Beverages",
      "Household",
      "Dairy",
      "Frozen",
      "Snacks",
    ],
    keywords: [
      "grocery",
      "food item",
      "provisions",
      "rice",
      "oil",
      "tomato",
      "indomie",
      "milk",
      "sugar",
      "flour",
    ],
  },

  furniture: {
    label: "Furniture",
    emoji: "🪑",
    description: "Furniture, interior decor, home fittings",
    terminology: {
      product: "Item",
      order: "Order",
      customer: "Customer",
      sale: "Sale",
    },
    productFields: ["material", "dimensions", "color", "assembly"],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: true,
      expiry: false,
    },
    defaultCategories: [
      "Sofas",
      "Beds",
      "Tables",
      "Chairs",
      "Wardrobes",
      "Decor",
    ],
    keywords: [
      "sofa",
      "chair",
      "table",
      "bed",
      "wardrobe",
      "shelf",
      "furniture",
      "mattress",
      "cabinet",
    ],
  },

  home_services: {
    label: "Home Services",
    emoji: "🔧",
    description: "Plumbers, electricians, cleaners, repairers",
    terminology: {
      product: "Service",
      order: "Booking",
      customer: "Client",
      sale: "Job",
    },
    productFields: ["duration", "serviceArea", "tools"],
    features: {
      delivery: false,
      productPhotos: true,
      catalog: true,
      appointments: true,
      inventory: false,
      expiry: false,
    },
    defaultCategories: [
      "Plumbing",
      "Electrical",
      "Cleaning",
      "AC Repair",
      "Painting",
      "Carpentry",
    ],
    keywords: [
      "repair",
      "fix",
      "plumber",
      "electrician",
      "clean",
      "ac",
      "painting",
      "service",
      "technician",
    ],
  },

  printing: {
    label: "Printing & Branding",
    emoji: "🖨️",
    description: "Print shops, branding, design services",
    terminology: {
      product: "Service",
      order: "Job",
      customer: "Client",
      sale: "Job",
    },
    productFields: ["size", "quantity", "material", "turnaround"],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: false,
      expiry: false,
    },
    defaultCategories: [
      "Flyers",
      "Banners",
      "T-Shirts",
      "Business Cards",
      "Stickers",
      "Branding",
    ],
    keywords: [
      "print",
      "flyer",
      "banner",
      "shirt",
      "branding",
      "logo",
      "design",
      "card",
      "sticker",
    ],
  },

  freelance: {
    label: "Freelancers & Creatives",
    emoji: "💻",
    description: "Designers, developers, writers, photographers",
    terminology: {
      product: "Service",
      order: "Project",
      customer: "Client",
      sale: "Project",
    },
    productFields: ["package", "deadline", "revisions", "deliverable"],
    features: {
      delivery: false,
      productPhotos: true,
      catalog: true,
      appointments: true,
      inventory: false,
      expiry: false,
    },
    defaultCategories: [
      "Design",
      "Development",
      "Writing",
      "Photography",
      "Video",
      "Marketing",
    ],
    keywords: [
      "design",
      "website",
      "logo",
      "write",
      "photo",
      "video",
      "content",
      "social media",
      "brand",
    ],
  },

  general: {
    label: "General Business",
    emoji: "🏪",
    description: "Any other business type",
    terminology: {
      product: "Product",
      order: "Order",
      customer: "Customer",
      sale: "Sale",
    },
    productFields: [],
    features: {
      delivery: true,
      productPhotos: true,
      catalog: true,
      appointments: false,
      inventory: true,
      expiry: false,
    },
    defaultCategories: ["Category 1", "Category 2", "Category 3"],
    keywords: [],
  },
};

export const getCategoryConfig = (category) =>
  CATEGORY_CONFIG[category] || CATEGORY_CONFIG.general;

export const ALL_CATEGORIES = Object.entries(CATEGORY_CONFIG).map(
  ([key, val]) => ({
    value: key,
    label: val.label,
    emoji: val.emoji,
    description: val.description,
  }),
);
